controller_list:
  - name: fake_ur5_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_gripper_controller
    joints:
      - robotiq_85_left_knuckle_joint
initial:  # Define initial robot poses.
  - group: ur5_arm
    pose: home